spring.application.name=chordify
spring.datasource.url=jdbc:sqlite:data/chordify.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.sql.init.mode=never
server.error.include-message=always
